name: Deploy Theme to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "vicsotheme.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFSSGaxVdVNP3rlEPM7xnWJWPeOj3erH74asbfzVusIz" >> ~/.ssh/known_hosts

      - name: Deploy via rsync
        run: |
          rsync -avz --delete \
            ./ \
            root@vicsotheme.com:/var/www/wordpress-dev/wp-content/themes/vicsotheme
